apiVersion: batch/v1
kind: Job
metadata:
  name: e2e
spec:
  template:
    spec:
      containers:
      - name: e2e
        image: davoska/edge-cloud-e2e:latest
      imagePullSecrets:
      - name: docker-cfg
      restartPolicy: Never
  backoffLimit: 3
