#
# A Kubernetes manifest file for the kafka broker in the cloud.
#
# Author: David Hurta
#

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-cloud
  name: kafka-cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-cloud
  template:
    metadata:
      labels:
        app: kafka-cloud
    spec:
      containers:
        - name: kafka-cloud
          image: docker.io/bitnami/kafka:3.6
          ports:
            - containerPort: 9092
              protocol: TCP
          volumeMounts:
            - name: kafka-data
              mountPath: /bitnami
          env:
            - name: KAFKA_CFG_NODE_ID
              value: "0"
            - name: KAFKA_CFG_PROCESS_ROLES
              value: "controller,broker"
            - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
              value: "0@localhost:9093"
            - name: KAFKA_CFG_LISTENERS
              value: "PLAINTEXT://:9092,CONTROLLER://:9093"
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka-cloud:9092"
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
            - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
              value: "PLAINTEXT"
      volumes:
        - name: kafka-data
          emptyDir: {}
      nodeSelector:
        node-role.kubernetes.io/cloud: ""
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-cloud
  name: kafka-cloud
spec:
  ports:
  - name: advertised-listener
    port: 9092
    protocol: TCP
    targetPort: 9092
  selector:
    app: kafka-cloud
  type: ClusterIP