#
# A Kubernetes manifest file for the kafka broker at the edge.
#
# Author: David Hurta
#

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-edge
  name: kafka-edge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-edge
  template:
    metadata:
      labels:
        app: kafka-edge
    spec:
      containers:
        - name: kafka-edge
          image: docker.io/bitnami/kafka:3.6
          ports:
            - containerPort: 9092
              protocol: TCP
          volumeMounts:
            - name: kafka-data
              mountPath: /bitnami
          env:
            - name: KAFKA_CFG_NODE_ID
              value: "0"
            - name: KAFKA_CFG_PROCESS_ROLES
              value: "controller,broker"
            - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
              value: "0@localhost:9093"
            - name: KAFKA_CFG_LISTENERS
              value: "PLAINTEXT://:9092,CONTROLLER://:9093"
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka-edge:9092"
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
            - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
              value: "PLAINTEXT" 
              # Retention of data for ~5 minutes (data is then marked)
            - name: KAFKA_CFG_LOG_RETENTION_MINUTES
              value: "5"
              # Delete then the marked data after 1 MB or after 5 minutes
            - name: KAFKA_CFG_LOG_ROLL_MS
              value: "300000"
            - name: KAFKA_CFG_LOG_SEGMENT_BYTES
              value: "1000000"
              # Check for marked data every 10 seconds
            - name: KAFKA_CFG_LOG_RETENTION_CHECK_INTERVAL_MS
              value: "10000"
      volumes:
        - name: kafka-data
          emptyDir: {}
      nodeSelector:
        node-role.kubernetes.io/edge: ""
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-edge
  name: kafka-edge
spec:
  ports:
  - name: advertised-listener
    port: 9092
    protocol: TCP
    targetPort: 9092
  selector:
    app: kafka-edge
  type: ClusterIP