#
# Configuration of a CNI plugin for KubeEdge.
#
# Author: David Hurta
#

---
- name: Configure reference CNI plugins per KubeEdge documentation
  #  Shell commands copied from the KubeEdge documentation by the KubeEdge Project Authors
  # https://release-1-19.docs.kubeedge.io/docs/faq/setup#cni-plugin-not-initializedcni-config-uninitialized
  ansible.builtin.shell: |
    cat >/etc/cni/net.d/10-containerd-net.conflist <<EOF
    {
      "cniVersion": "1.0.0",
      "name": "containerd-net",
      "plugins": [
        {
          "type": "bridge",
          "bridge": "cni0",
          "isGateway": true,
          "ipMasq": true,
          "promiscMode": true,
          "ipam": {
            "type": "host-local",
            "ranges": [
              [{
                "subnet": "10.88.0.0/16"
              }],
              [{
                "subnet": "2001:db8:4860::/64"
              }]
            ],
            "routes": [
              { "dst": "0.0.0.0/0" },
              { "dst": "::/0" }
            ]
          }
        },
        {
          "type": "portmap",
          "capabilities": {"portMappings": true}
        }
      ]
    }
    EOF
    systemctl restart containerd.service
  args:
    creates: /etc/cni/net.d/10-containerd-net.conflist
