#
# A setup of edge nodes.
#
# Author: David Hurta
#

---
- name: Label edge nodes
  delegate_to: localhost
  ansible.builtin.command:
    argv:
      - kubectl
      - label
      - nodes
      - "{{ kube_node_name }}"
      - node-role.kubernetes.io/edge=
      - --kubeconfig
      - kubeconfig
