#
# A setup of infrastructure nodes.
#
# Author: David Hurta
#

---
- name: Label infra nodes
  # --k3s-extra-args '--node-label node-role.kubernetes.io/worker=worker' cannot be used
  # see: https://github.com/kubernetes-sigs/kind/issues/2724#issuecomment-1102680869
  delegate_to: localhost
  ansible.builtin.command:
    argv:
      - kubectl
      - label
      - nodes
      - "{{ kube_node_name }}"
      - node-role.kubernetes.io/infra=
      - --kubeconfig
      - kubeconfig

- name: Taint Kubernetes infra nodes as node-role.kubernetes.io/infra:NoSchedule
  delegate_to: localhost
  ansible.builtin.command:
    argv:
      - kubectl
      - taint
      - node
      - "{{ kube_node_name }}"
      - node-role.kubernetes.io/infra:NoSchedule
      - --overwrite
      - --kubeconfig
      - kubeconfig
