---
- name: Startup configuration
  import_playbook: startup.yaml
- name: Create a K3s cluster
  import_playbook: k3s-setup.yaml
- name: Post-Install configuration
  import_playbook: post-install.yaml
