---
- name: Startup configuration
  import_playbook: startup.yaml
- name: Create a MicroK8s cluster
  import_playbook: microk8s-setup.yaml
- name: Post-Install configuration
  import_playbook: post-install.yaml
