#
# A helm values file for a Kubernetes metrics server.
#
# Author: David Hurta
#

nodeSelector:
  node-role.kubernetes.io/control-plane: ""
tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
  - key: "node-role.kubernetes.io/master"
    operator: "Exists"
    effect: "NoSchedule"
args: # INSECURE; to set up securely, see: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm/#cannot-use-the-metrics-server-securely-in-a-kubeadm-cluster
  - --kubelet-insecure-tls