#
# A workflow to check and validate Terraform files.
#
# Author: David Hurta
#

name: Check and validate Terraform

on:
  push:
    branches: [ "master" ]
    paths:
      - "terraform/*"

  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      # To use terraform CLI
      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        id: init
        run: terraform -chdir=terraform init
      
      - name: Terraform fmt
        id: fmt
        run: terraform -chdir=terraform fmt

      - name: Check for changes
        run: git diff --exit-code

      - name: Terraform validate
        id: validate
        run: terraform -chdir=terraform validate

      - name: Check for changes
        run: git diff --exit-code
